export const AGENT_STATES = ["IDLE","UNDERSTANDING","INSPECTING","NEEDS_CLARIFICATION","PLANNING","GENERATING","VALIDATING","READY_FOR_REVIEW","REVISING","AWAITING_APPROVAL","APPLYING","COMPLETED","FAILED","CANCELLED"] as const
export type AgentState = typeof AGENT_STATES[number]

export const VALID_TRANSITIONS: Record<AgentState, AgentState[]> = {
  IDLE: ["UNDERSTANDING"], UNDERSTANDING: ["INSPECTING","NEEDS_CLARIFICATION"],
  INSPECTING: ["NEEDS_CLARIFICATION","PLANNING"], NEEDS_CLARIFICATION: ["PLANNING"],
  PLANNING: ["GENERATING"], GENERATING: ["VALIDATING"],
  VALIDATING: ["READY_FOR_REVIEW","GENERATING"], READY_FOR_REVIEW: ["REVISING","AWAITING_APPROVAL"],
  REVISING: ["VALIDATING"], AWAITING_APPROVAL: ["APPLYING","REVISING"],
  APPLYING: ["COMPLETED","FAILED"], COMPLETED: ["IDLE"], FAILED: ["PLANNING","CANCELLED"], CANCELLED: ["IDLE"],
}

export const STATE_LABELS: Record<AgentState, string> = {
  IDLE: "En attente", UNDERSTANDING: "Analyse de la demande", INSPECTING: "Inspection du workflow",
  NEEDS_CLARIFICATION: "Question de clarification", PLANNING: "Planification", GENERATING: "Génération de la proposition",
  VALIDATING: "Validation", READY_FOR_REVIEW: "Prêt pour révision", REVISING: "Révision en cours",
  AWAITING_APPROVAL: "En attente d'approbation", APPLYING: "Application en cours", COMPLETED: "Terminé",
  FAILED: "Échec", CANCELLED: "Annulé",
}
